[package]
name = "rust_kafka_consumer_practise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.10.0"
tokio = { version = "1", features = ["full"] }
env_logger = "0.9"
